version: '3.8'

services:
  app:
    build:
      context: .
    container_name: ictransport
    command: /bin/sh "/app/docker/app.sh"
    volumes:
      - .:/app
    ports:
      - 6060:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - '1435:5432'
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data/
      - db-logs:/var/log/postgresql

volumes:
  db-data:
  db-logs:

#docker-compose down -v